"""change user

Revision ID: 7e8043bb18ab
Revises: 20dd6bfe4a45
Create Date: 2025-09-29 16:44:01.843200
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e8043bb18ab'
down_revision: Union[str, None] = '20dd6bfe4a45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=125),
               existing_nullable=False)
    op.create_unique_constraint(None, 'users', ['id'])
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'id',
               existing_type=sa.String(length=125),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
